<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.38.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest">
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\wwwroot</PackagePath>
    </Content>
  </ItemGroup>

</Project>
